######################################################################
# Automatically generated by qmake (3.0) Mon 31. Mar 14:04:37 2014
######################################################################

TEMPLATE = app
TARGET = splittingVisualiser
INCLUDEPATH += .

# Input
HEADERS += splittingVisualiser.h
SOURCES += main.cpp splittingVisualiser.cpp
